import builtins
from typing import Dict

class Client:
    def __init__(self, timeout: int): ...
    async def get(self, url: str, params: Dict[str, str]) -> str: ...

class TimeoutError(builtins.TimeoutError): ...
class ConnectError(Exception): ...
class RequestError(Exception): ...
class BadStatusCodeError(Exception): ...
class BodyError(Exception): ...
class BuilderError(Exception): ...
class DecodeError(Exception): ...
class RedirectError(Exception): ...
class RetryError(Exception): ...
